(function(){
	//4个表格切换
	 $(".liu_but").click(function(){
	 	$(".liu_but").addClass("b0b0b0");
	 	$(".liu_but").addClass("bgffffff");
	 	$(this).removeClass("b0b0b0");
	 	$(this).removeClass("bgffffff");
	 });
})();